Repository otus-devops-2020-02-lineate/search_engine_microservices, pull requests merged in 2020-07, with the labels that each got.

#2 Add terraform to launch kubernetes cluster
  CHANGELOG.md
  README.md
  docs/Terraform-runbook.md
  terraform/backend.tf
  terraform/main.tf
  terraform/outputs.tf
  terraform/storage/main.tf
  terraform/storage/terraform.tfvars.example
  terraform/storage/variables.tf
  terraform/terraform.tfvars.example
  terraform/variables.tf
Labels: enhancement, terraform

#3 Add manual application deployment with helm
  .gitignore
  CHANGELOG.md
  charts/crawler/Chart.yaml
  charts/crawler/templates/_helpers.tpl
  charts/crawler/templates/deployment.yaml
  charts/crawler/values.yaml
  charts/search-engine/Chart.yaml
  charts/search-engine/requirements.lock
  charts/search-engine/requirements.yaml
  charts/search-engine/values.yaml
  charts/ui/Chart.yaml
  charts/ui/templates/_helpers.tpl
  charts/ui/templates/deployment.yaml
  charts/ui/templates/ingress.yaml
  charts/ui/templates/service.yaml
  charts/ui/values.yaml
  docs/Helm-charts-running.md
  docs/Helm-installation.md
Labels: enhancement, kubernetes

#4 Makefile
  Makefile
Labels: makefile

#5 README: add notes about Helm manual release
  README.md
Labels: docs

#6 README: correction
  README.md
Labels: docs
